name: Descent 3 Build

on:
  push:
    branches: [ "midnite_main", "main" ]
  pull_request:
    branches: [ "midnite_main", "main" ]

jobs:
  build:
    strategy:
      fail-fast: false

      matrix:
        os: [{
          runner: windows-latest,
          preset: win-vcpkg,
          triplet: x86-windows
        }, {
          runner: macos-latest,
          preset: mac,
          triplet: x64-osx
        }]
        build_type: [Debug, Release]

    runs-on: ${{ matrix.os.runner }}

    env:
      VCPKG_DEFAULT_TRIPLET: ${{ matrix.os.triplet }}

    steps:
    - uses: actions/checkout@v4

    - name: Install macOS dependencies
      if: ${{ matrix.os.preset == 'mac' }}
      run: |
        # Note this is x86_64 Homebrew
        /usr/local/bin/brew install sdl12-compat
        curl --output-dir /tmp -fsSLO https://github.com/XQuartz/XQuartz/releases/download/XQuartz-2.8.5/XQuartz-2.8.5.pkg
        sudo installer -pkg /tmp/XQuartz-2.8.5.pkg -target LocalSystem

    - uses: lukka/run-vcpkg@v11
      with:
        vcpkgGitCommitId: "501cb01e517ee5689577bb01ba8bd1b4c1041a53"

    - uses: lukka/run-cmake@v10
      with:
        configurePreset: ${{matrix.os.preset}}
        buildPreset: ${{matrix.os.preset}}
        buildPresetAdditionalArgs: "['--config ${{matrix.build_type}}']"

    - name: 'Upload Artifacts'
      uses: actions/upload-artifact@v4
      with:
        name: build_${{matrix.build_type}}
        path: "${{github.workspace}}/builds/${{matrix.os.preset}}/Descent3/${{matrix.build_type}}"
